export let skins: { [key: string]: string } = {
  "1F3FB": "l",
  "1F3FC": "ml",
  "1F3FD": "m",
  "1F3FE": "md",
  "1F3FF": "d",
  "1F3FB-1F3FB": "l_l",
  "1F3FB-1F3FC": "l_ml",
  "1F3FB-1F3FD": "l_m",
  "1F3FB-1F3FE": "l_md",
  "1F3FB-1F3FF": "l_d",
  "1F3FC-1F3FB": "ml_l",
  "1F3FC-1F3FC": "ml_ml",
  "1F3FC-1F3FD": "ml_m",
  "1F3FC-1F3FE": "ml_md",
  "1F3FC-1F3FF": "ml_d",
  "1F3FD-1F3FB": "m_l",
  "1F3FD-1F3FC": "m_ml",
  "1F3FD-1F3FD": "m_m",
  "1F3FD-1F3FE": "m_md",
  "1F3FD-1F3FF": "m_d",
  "1F3FE-1F3FB": "md_l",
  "1F3FE-1F3FC": "md_ml",
  "1F3FE-1F3FD": "md_m",
  "1F3FE-1F3FE": "md_md",
  "1F3FE-1F3FF": "md_d",
  "1F3FF-1F3FB": "d_l",
  "1F3FF-1F3FC": "d_ml",
  "1F3FF-1F3FD": "d_m",
  "1F3FF-1F3FE": "d_md",
  "1F3FF-1F3FF": "d_d",
};

export const category = {
  Symbols: "Символы",
  Activities: "Деятельность",
  Flags: "Флаги",
  "Travel & Places": "Путешествия и места",
  "Food & Drink": "Еда и напитки",
  "Animals & Nature": "Животные и природа",
  "People & Body": "Люди и тело",
  Objects: "Объекты",
  Component: "Компонент",
  "Smileys & Emotion": "Смайлики и эмодзи",
};
export const subcategory = {
  keycap: "клавиатура",
  "other-symbol": "другой символ",
  game: "игра",
  alphanum: "алфавит",
  "country-flag": "флаг страны",
  "sky & weather": "небо и погода",
  "place-other": "место-другое",
  "place-geographic": "географическое место",
  "place-map": "карта места",
  "food-prepared": "продукты питания",
  "food-vegetable": "еда-овощи",
  "plant-other": "растение-другое",
  "plant-flower": "растение-цветок",
  "food-fruit": "еда-фрукт",
  "food-asian": "еда-азиатская",
  "food-sweet": "еда-сладкое",
  dishware: "посуда",
  drink: "напиток",
  event: "событие",
  "person-fantasy": "человек-фантазия",
  flag: "флаг",
  clothing: "одежда",
  "award-medal": "награда-медаль",
  music: "музыка",
  "light & video": "свет и видео",
  sport: "спорт",
  "av-symbol": "av-символ",
  "arts & crafts": "искусство и ремёсла",
  "musical-instrument": "музыкальный инструмент",
  "person-sport": "человек-спорт",
  "person-activity": "человек-активность",
  "transport-ground": "транспорт-земля",
  "place-building": "строительство",
  "transport-sign": "транспортный знак",
  "subdivision-flag": "подразделение-флаг",
  "book-paper": "книга-бумага",
  tool: "инструмент",
  "skin-tone": "тон кожи",
  "animal-mammal": "животное-млекопитающее",
  "animal-reptile": "животное-рептилия",
  "animal-marine": "животное-морской",
  "animal-bug": "животное-жук",
  "animal-bird": "животное-птица",
  "animal-amphibian": "животное-амфибия",
  "body-parts": "части тела",
  emotion: "эмоция",
  "hand-single-finger": "рука-один палец",
  "hand-fingers-closed": "рука-пальцы-закрытые",
  "hand-fingers-open": "рука-пальцы-открытые",
  "hand-fingers-partial": "пальцы рук - частично",
  hands: "руки",
  "person-symbol": "человек-символ",
  person: "человек",
  "person-role": "человек-роль",
  family: "семья",
  "face-costume": "лицо-костюм",
  "face-negative": "лицо-отрицательное",
  "person-gesture": "лицо-жест",
  "hand-prop": "реквизит",
  medical: "медицинский",
  heart: "сердце",
  geometric: "геометрический",
  money: "деньги",
  currency: "валюта",
  "transport-air": "транспорт-воздух",
  computer: "компьютер",
  office: "офис",
  writing: "письмо",
  phone: "телефон",
  science: "наука",
  sound: "звук",
  mail: "почта",
  warning: "предупреждение",
  arrow: "стрелка",
  lock: "замок",
  religion: "религия",
  "place-religious": "место-религия",
  time: "время",
  "other-object": "другой объект",
  "face-smiling": "лицо-улыбка",
  "face-tongue": "лицо-язык",
  "face-sleepy": "лицо-сон",
  "face-affection": "лицо-ласка",
  "face-glasses": "лицо-очки",
  "face-neutral-skeptical": "лицо-нейтрально-скептическое",
  "face-concerned": "лицо озабоченное",
  "face-unwell": "лицо-нездоровое",
  "cat-face": "кошачье лицо",
  "monkey-face": "лицо обезьяны",
  "transport-water": "транспорт-вода",
  household: "домашнее хозяйство",
  "person-resting": "человек-отдых",
  hotel: "отель",
  math: "математика",
  "face-hand": "лицо-рука",
  "face-hat": "лицо-шляпа",
  "food-marine": "еда-море",
  punctuation: "пунктуация",
  gender: "пол",
  zodiac: "зодиак",
};
